### ISSUE TITLE
If 1 container finishes its job with some test failures then all other containers stop their jobs

### ISSUE THREAD

**Issue by r4f47** [0xIslamTaha/orchestrator#11]
Hi,
First of all thank you very much for sharing this useful tool :)
I'm not sure if it's on purpose, but I've noticed that after 1 of the containers finishes its chunk of the test suite with errors, then all other containers are stopping their work without finishing their part. I think it's caused by using Promise.all in orchestrator.js line 286 - what do you think about using Promise.allSettled instead, so we can wait until all containers finish their jobs and then check if any of promises was rejected?
Thanks,
Rafal

**Comment by SinQA** [comment]
Hi, I really need this PR is merged to `master` and release new version for this tool.

**Comment by 0xIslamTaha** [comment]
> Hi, I really need this PR is merged to `master` and release new version for this tool. 
> 

Hi,
I added some comments to the PR, Im not sure if the developer has time to do it.

In couple of days, I will push it to master and release the new version

**Comment by 0xIslamTaha** [comment]
@r4f47 
Thanks for your PR 
@SinQA version 2.0.0 has been released 🔥
