### ISSUE TITLE
Question on set up

### ISSUE THREAD

**Issue by dennismail4u** [0xIslamTaha/orchestrator#25]
Hello,
I have a docker container where my current tests running. Is this set up works like running multiple containers from my current one to parallize my test files? Just wanted to understand how it works if its a recommended way.

Thanks
Dennis

**Comment by 0xIslamTaha** [comment]
@dennismail4u  You can just run the orchestrator command from the host machine. It will check your specs, create the need containers and it will manage it for you. 

Here is an example: https://github.com/0xIslamTaha/orchestrator-public-use-case
